---
resources:
- name: this-git
  type: git
  source:
    uri: https://github.com/ships/dockerfiles
    paths: [ubuntu-git]

- name: this-jq
  type: git
  source:
    uri: https://github.com/ships/dockerfiles
    paths: [ubuntu-jq]

- name: base-ubuntu
  type: docker-image
  source:
    repository: ubuntu

- name: ubuntu-jq
  type: docker-image
  source:
    repository: eveships/ubuntu-jq
    username: ((dockerhub_ships.username))
    password: ((dockerhub_ships.password))

- name: ubuntu-git
  type: docker-image
  source:
    repository: eveships/ubuntu-git
    username: ((dockerhub_ships.username))
    password: ((dockerhub_ships.password))

jobs:
- name: rebuild-ubuntu-git
  plan:
  - aggregate:
    - get: base-ubuntu
      trigger: true
    - get: this
      resource: this-git
      trigger: true
  - put: ubuntu-git
    params:
      build: this/ubuntu-git

- name: rebuild-ubuntu-jq
  plan:
  - aggregate:
    - get: base-ubuntu
      trigger: true
    - get: this
      resource: this-jq
      trigger: true
  - put: ubuntu-jq
    params:
      build: this/ubuntu-jq
