---
resources:
- name: this-git
  type: git
  source:
    uri: https://github.com/ships/dockerfiles
    paths: [ubuntu-git]

- name: this-jq
  type: git
  source:
    uri: https://github.com/ships/dockerfiles
    paths: [ubuntu-jq]

- name: concourse-generics
  type: git
  source:
    uri: https://github.com/ships/concourse-generics

- name: base-ubuntu
  type: registry-image
  source:
    repository: ubuntu
    tag: "20.04"
    username: ((dockerhub-ships.username))
    password: ((dockerhub-ships.password))

- name: ubuntu-jq
  type: registry-image
  source:
    repository: eveships/ubuntu-jq
    tag: latest
    username: ((dockerhub-ships.username))
    password: ((dockerhub-ships.password))

- name: ubuntu-git
  type: registry-image
  source:
    repository: eveships/ubuntu-git
    tag: latest
    username: ((dockerhub-ships.username))
    password: ((dockerhub-ships.password))

jobs:
- name: rebuild-ubuntu-git
  plan:
  - in_parallel:
    - get: concourse-generics
    - get: base-ubuntu
      trigger: true
    - get: this
      resource: this-git
      trigger: true

  - task: build
    file: concourse-generics/toolchains/docker/build.yml
    privileged: true
    input_mapping:
      src: this
    params:
      CONTEXT: ./ubuntu-git
  - put: ubuntu-git
    params:
      image: image/image.tar

- name: rebuild-ubuntu-jq
  plan:
  - in_parallel:
    - get: concourse-generics
    - get: base-ubuntu
      trigger: true
    - get: this
      resource: this-jq
      trigger: true
  - task: build
    file: concourse-generics/toolchains/docker/build.yml
    privileged: true
    input_mapping:
      src: this
    params:
      CONTEXT: ./ubuntu-jq
  - put: ubuntu-jq
    params:
      image: image/image.tar
