---
resources:
- name: this-git
  type: git
  source:
    uri: https://github.com/ships/dockerfiles
    paths: [ubuntu-git]

- name: this-jq
  type: git
  source:
    uri: https://github.com/ships/dockerfiles
    paths: [ubuntu-jq]

- name: this-alpine-nc
  type: git
  source:
    uri: https://github.com/ships/dockerfiles
    paths: [alpine-nc]

- name: this-act-plusplus
  type: git
  source:
    uri: https://github.com/ships/dockerfiles
    paths: [act-plusplus]

- name: concourse-generics
  type: git
  source:
    uri: https://github.com/ships/concourse-generics

- name: base-ubuntu
  type: registry-image
  source:
    repository: ubuntu
    tag: "20.04"
    username: ((dockerhub-ships.username))
    password: ((dockerhub-ships.password))

- name: base-act
  type: registry-image
  source:
    repository: ghcr.io/catthehacker/ubuntu
    tag: "act-latest"

- name: base-alpine
  type: registry-image
  source:
    repository: alpine
    tag: "latest"
    username: ((dockerhub-ships.username))
    password: ((dockerhub-ships.password))

- name: ubuntu-jq
  type: registry-image
  source:
    repository: eveships/ubuntu-jq
    tag: latest
    username: ((dockerhub-ships.username))
    password: ((dockerhub-ships.password))

- name: ubuntu-git
  type: registry-image
  source:
    repository: eveships/ubuntu-git
    tag: latest
    username: ((dockerhub-ships.username))
    password: ((dockerhub-ships.password))

- name: alpine-nc
  type: registry-image
  source:
    repository: eveships/alpine-nc
    tag: latest
    username: ((dockerhub-ships.username))
    password: ((dockerhub-ships.password))

- name: act-plusplus
  type: registry-image
  source:
    repository: eveships/act-plusplus
    tag: latest
    username: ((dockerhub-ships.username))
    password: ((dockerhub-ships.password))

jobs:
- name: rebuild-ubuntu-git
  plan:
  - in_parallel:
    - get: concourse-generics
    - get: base-ubuntu
      trigger: true
    - get: src
      resource: this-git
      trigger: true

  - task: build
    file: concourse-generics/toolchains/docker/build.yml
    privileged: true
    params:
      CONTEXT: ./ubuntu-git
  - put: ubuntu-git
    params:
      image: image/image.tar

- name: rebuild-ubuntu-jq
  plan:
  - in_parallel:
    - get: concourse-generics
    - get: base-ubuntu
      trigger: true
    - get: src
      resource: this-jq
      trigger: true
  - task: build
    file: concourse-generics/toolchains/docker/build.yml
    privileged: true
    params:
      CONTEXT: ./ubuntu-jq
  - put: ubuntu-jq
    params:
      image: image/image.tar

- name: rebuild-act-plusplus
  plan:
  - in_parallel:
    - get: concourse-generics
    - get: base-act
      trigger: true
    - get: src
      resource: this-act-plusplus
      trigger: true
  - task: build
    file: concourse-generics/toolchains/docker/build.yml
    privileged: true
    params:
      CONTEXT: ./act-plusplus
  - put: act-plusplus
    params:
      image: image/image.tar

- name: rebuild-alpine-nc
  plan:
  - in_parallel:
    - get: concourse-generics
    - get: base-alpine
      trigger: true
    - get: src
      resource: this-alpine-nc
      trigger: true

  - task: build
    file: concourse-generics/toolchains/docker/build.yml
    privileged: true
    params:
      CONTEXT: ./alpine-nc
  - put: alpine-nc
    params:
      image: image/image.tar
